package shiiba

import (
	"bytes"
	"testing"
	"time"
)

func TestShowCalendar(t *testing.T) {
	buf := &bytes.Buffer{}
	now := time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)
	ShowCalendar(buf, now, 365)
	output := buf.String()

	expected := `.....................................................
.....................................................
.....................................................
.....................................................
....................................................
....................................................
....................................................
`
	if expected != output {
		t.Errorf("fail: calendar output invalid want %v but %v", expected, output)
	}
}

func TestShowCalendarWithWeekday(t *testing.T) {
	buf := &bytes.Buffer{}
	now := time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)
	ShowCalendar(buf, now, 365, IsShowWeekday(true))
	output := buf.String()

	expected := `    .....................................................
Mon .....................................................
    .....................................................
Wed .....................................................
    ....................................................
Fri ....................................................
    ....................................................
`
	if expected != output {
		t.Errorf("fail: calendar output invalid want %v but %v", expected, output)
	}
}

func TestShowCalendarWithMonth(t *testing.T) {
	buf := &bytes.Buffer{}
	now := time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)
	ShowCalendar(buf, now, 365, IsShowMonth(true))
	output := buf.String()

	expected := ` Jan Feb Mar  Apr May Jun  Jul Aug Sep  Oct Nov Dec
.....................................................
.....................................................
.....................................................
.....................................................
....................................................
....................................................
....................................................
`
	if expected != output {
		t.Errorf("fail: calendar output invalid want %v but %v", expected, output)
	}
}

func TestShowCalendarWithMonthAndWeekday(t *testing.T) {
	buf := &bytes.Buffer{}
	now := time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)
	ShowCalendar(buf, now, 365, IsShowMonth(true), IsShowWeekday(true))
	output := buf.String()

	expected := `     Jan Feb Mar  Apr May Jun  Jul Aug Sep  Oct Nov Dec
    .....................................................
Mon .....................................................
    .....................................................
Wed .....................................................
    ....................................................
Fri ....................................................
    ....................................................
`
	if expected != output {
		t.Errorf("fail: calendar output invalid want %v but %v", expected, output)
	}
}

func TestShowCalendarWithActivities(t *testing.T) {
	buf := &bytes.Buffer{}
	now := time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)
  ShowCalendar(buf, now, 365, func(args *Configs) {
    args.ActivityProvider = NullProvider
  })
	output := buf.String()

	expected := `.....................................................
.....................................................
.....................................................
.....................................................
....................................................
....................................................
....................................................
`
	if expected != output {
		t.Errorf("fail: calendar output invalid want %v but %v", expected, output)
	}
}
